# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_executor/order_executor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'order_executor/order_executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#order_executor/order_executor.proto\x12\x0eorder_executor\"\r\n\x0bPingRequest\"E\n\x0cPingResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x12\x13\n\x0b\x65xecutor_id\x18\x02 \x01(\t\x12\x11\n\tis_leader\x18\x03 \x01(\x08\x32Y\n\x14OrderExecutorService\x12\x41\n\x04Ping\x12\x1b.order_executor.PingRequest\x1a\x1c.order_executor.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor.order_executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=55
  _globals['_PINGREQUEST']._serialized_end=68
  _globals['_PINGRESPONSE']._serialized_start=70
  _globals['_PINGRESPONSE']._serialized_end=139
  _globals['_ORDEREXECUTORSERVICE']._serialized_start=141
  _globals['_ORDEREXECUTORSERVICE']._serialized_end=230
# @@protoc_insertion_point(module_scope)
